spring.cloud.stream:
  function:
    definition: countVotes;outputResults
  bindings:
    countVotes-in-0.destination: votes
    countVotes-out-0.destination: counts
    outputResults-in-0.destination: counts
    outputResults-in-1.destination: polls
    outputResults-out-0.destination: results
#    results-in-0.destination: counting
#    results-in-1.destination: activities
#    results-out-0.destination: results
spring.application.name: results
spring.cloud.stream.kafka.streams.binder:
  configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
    commit.interval.ms: 1000