-- CREATE USER 'replicator' IDENTIFIED BY 'replpass';
-- CREATE USER 'debezium' IDENTIFIED BY 'dbz';
-- GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'replicator';
-- GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT  ON *.* TO 'debezium';

CREATE DATABASE polls;
GRANT ALL PRIVILEGES ON polls.* TO 'mysqluser'@'%';

USE polls;

DROP TABLE IF EXISTS POLL_TOPICS;

CREATE TABLE IF NOT EXISTS POLL_TOPICS
(
    id   SERIAL PRIMARY KEY,
    description text NOT NULL
);
