version: '2'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    container_name: zookeeper
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    container_name: kafka
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  mysql:
    image:   quay.io/debezium/example-mysql:${DEBEZIUM_VERSION}
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 30s
      timeout: 30s
      retries: 5
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
  pollsweb:
    image: polls-db:0.0.1-SNAPSHOT
    container_name: pollsweb
    depends_on:
      - mysql
    ports:
     - 8080:8080
    environment:
     - MYSQL_HOST=mysql
     - MYSQL_USERNAME=mysqluser
     - MYSQL_PASSWORD=mysqlpw
     - MYSQL_DB=polls  
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s    
  connect:
    image: quay.io/debezium/connect:${DEBEZIUM_VERSION}
    container_name: connect
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses